name: Main PR
on: 
  push:
    branches:
      - main
   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Source code from the latest commit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Download Salesforce CLI
      - name: Download Salesforce CLI
        run: |
          wget -qO sfdx.tar.xz https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir sfdx
          tar xJf sfdx.tar.xz -C sfdx --strip-components 1
          sudo mv sfdx /usr/local/lib/
          sudo ln -s /usr/local/lib/sfdx/bin/sfdx /usr/local/bin/sfdx
        
      # Ensure sfdx is added to PATH
      - name: Add Salesforce CLI to PATH
        run: echo 'export PATH=$PATH:/usr/local/bin/sfdx/bin' >> $HOME/.bashrc && source $HOME/.bashrc

      # Create server key file
      - name: Create server key file
        run: |
          touch server.key
          echo -e "${{ secrets.SF_CICD_SERVERKEY }}" >> server_main.key  
          
      # Authorization with DevHub
      - name: Authorize DevHub
        run:  sfdx force:auth:jwt:grant --clientid "${{ secrets.SF_CLIENT_ID }}" --username "${{ secrets.SF_CICD_USERNAME }}" --jwtkeyfile server.key --setdefaultdevhubusername --instanceurl https://login.salesforce.com
      # Deploy changes
      - name: Deploy changes
        run: sfdx force:source:deploy -p NoProject/force-app/main/default -u ${{ secrets.SF_CICD_USERNAME }} --json 
        
